name: Rust

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust workflow
    runs-on: ubuntu-latest

    steps:
    - name: ğŸš€ Checkout code
      uses: actions/checkout@v4

    - name: ğŸ“Œ Remember short commit ID
      run: |
        calculated_sha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculated_sha" >> $GITHUB_ENV

    - name: ğŸ”¨ Build
      run: cargo build --release

    - name: âœ… Run tests
      run: cargo test --no-fail-fast

    - name: ğŸ“ Check formatting
      run: cargo fmt --check

    - name: ğŸ” Linting
      run: cargo clippy -- -D warnings

    - name: ğŸ’¾ Saving artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rustap-${{ env.COMMIT_SHORT_SHA }}
        path: target/release/rustapp
        if-no-files-found: error
